import type { CreatorStoryAssistantTargetSection } from "../types";
import type { CreatorAssistantSkill } from "./types";

export const creatorAssistantSkills: CreatorAssistantSkill[] = [
  {
    id: "project",
    label: "全工程",
    purpose: "从整体角度诊断并补强故事工程，但仍然只返回可审核的字段 patch。",
    defaultAction: "expand-concept",
    editableFields: [
      "title",
      "logline",
      "synopsis",
      "audience",
      "genres",
      "moods",
      "tags",
      "world.*",
      "narrative.*",
      "storyOutline.*",
      "structure.acts",
      "characters.*",
      "assets.title",
      "assets.prompt",
      "assets.notes",
      "interaction.*",
      "visual.stylePrompt",
      "runtimePolicy.styleGuide",
    ],
    readonlyFields: [
      "id",
      "schemaVersion",
      "createdAt",
      "updatedAt",
      "generation",
      "publish",
      "playtests",
      "openingPackage",
      "fixedRuntimePackages",
      "assets.url",
      "assets.status",
      "assets.provider",
      "assets.model",
      "assets.key",
      "characters.referenceImageUrl",
      "characters.referenceImageStatus",
    ],
    patchRootKeys: [
      "title",
      "logline",
      "synopsis",
      "audience",
      "genres",
      "moods",
      "tags",
      "world",
      "narrative",
      "storyOutline",
      "structure",
      "characters",
      "assets",
      "interaction",
      "visual",
      "runtimePolicy",
    ],
    promptGuidance:
      "You may suggest improvements across the whole StoryProject. Keep changes coherent across concept, world, outline, characters, interaction, and visual direction.",
    quickActions: ["诊断缺口", "补强设定", "压缩试玩", "统一风格"],
    outputMode: "proposal",
  },
  {
    id: "basics",
    label: "基础信息",
    purpose: "补齐作品定位，让后台列表、发布包装和模型理解作品核心。",
    defaultAction: "expand-concept",
    editableFields: [
      "title",
      "synopsis",
      "audience",
      "genres",
      "moods",
      "tags",
      "narrative.protagonist",
      "narrative.coreConflict",
    ],
    readonlyFields: ["logline", "storyOutline", "world", "characters", "assets", "publish", "generation"],
    patchRootKeys: ["title", "synopsis", "audience", "genres", "moods", "tags", "narrative"],
    promptGuidance:
      "Focus only on title, synopsis, audience, genres, moods, tags, narrative.protagonist, and narrative.coreConflict. In the current editor, these fields form the basic positioning section.",
    quickActions: ["补作品简介", "明确玩家位置", "强化核心冲突", "整理标签"],
    outputMode: "patch",
  },
  {
    id: "world",
    label: "世界观",
    purpose: "稳定故事发生环境、规则、地点和叙事调性。",
    defaultAction: "expand-concept",
    editableFields: ["world.setting", "world.rules", "world.locations", "world.tone"],
    readonlyFields: ["characters", "storyOutline", "assets", "interaction", "publish", "generation"],
    patchRootKeys: ["world"],
    promptGuidance:
      "Focus only on world.setting, world.rules, world.tone, and world.locations. Make the rules concrete enough to prevent runtime generation drift.",
    quickActions: ["补世界规则", "强化地点", "统一调性", "防止跑偏"],
    outputMode: "patch",
  },
  {
    id: "narrative",
    label: "叙事核心",
    purpose: "明确玩家视角、核心冲突、谜题、章节目标和创作者备注。",
    defaultAction: "expand-concept",
    editableFields: [
      "narrative.protagonist",
      "narrative.coreConflict",
      "narrative.keyMysteries",
      "narrative.chapterGoals",
      "narrative.creatorNotes",
    ],
    readonlyFields: ["world", "assets", "publish", "generation"],
    patchRootKeys: ["narrative"],
    promptGuidance:
      "Focus only on protagonist/player position, core conflict, key mysteries, chapter goals, and creator notes. Do not rewrite world rules or asset data.",
    quickActions: ["强化冲突", "补谜题", "明确章节目标", "整理备注"],
    outputMode: "patch",
  },
  {
    id: "outline",
    label: "故事蓝图",
    purpose: "建立主线目标、阶段推进、必达节点、关系护栏和结局方向。",
    defaultAction: "build-outline",
    editableFields: [
      "logline",
      "storyOutline.mainGoal",
      "storyOutline.phaseOutline",
      "storyOutline.requiredBeats",
      "storyOutline.relationshipArc",
      "storyOutline.supportingCast",
      "storyOutline.endingDirection",
      "storyOutline.guardrails",
      "structure.acts",
    ],
    readonlyFields: ["world", "characters.referenceImageUrl", "assets", "publish", "generation"],
    patchRootKeys: ["logline", "storyOutline", "structure"],
    promptGuidance:
      "Focus only on logline, storyOutline, and structure.acts/scenes. The logline is the story blueprint's core promise. Preserve player agency while keeping required beats and guardrails clear.",
    quickActions: ["生成主线目标", "压缩试玩路径", "补必达节点", "补防跑偏规则"],
    outputMode: "patch",
  },
  {
    id: "characters",
    label: "角色",
    purpose: "补齐角色卡、关系定位、人物功能、声音描述和角色参考图提示词。",
    defaultAction: "create-characters",
    editableFields: [
      "characters.id",
      "characters.name",
      "characters.role",
      "characters.persona",
      "characters.relationshipToPlayer",
      "characters.visualNotes",
      "characters.voiceNotes",
      "characters.referenceImagePrompt",
      "characters.locked",
    ],
    readonlyFields: [
      "characters.referenceImageUrl",
      "characters.referenceImageStatus",
      "characters.referenceImageKey",
      "assets.url",
      "assets.status",
      "publish",
      "generation",
    ],
    patchRootKeys: ["characters"],
    promptGuidance:
      "Focus only on character cards, relationship positions, visual notes, voice notes, and reference image prompts. Respect locked characters. Never invent reference image URLs or image status.",
    quickActions: ["补主角", "补关系角色", "强化人物关系", "生成参考图提示词"],
    outputMode: "patch",
  },
  {
    id: "assets",
    label: "资产库",
    purpose: "为封面、首场、角色参考和风格参考生成素材槽位说明与提示词。",
    defaultAction: "expand-concept",
    editableFields: ["assets.id", "assets.kind", "assets.title", "assets.prompt", "assets.characterId", "assets.notes"],
    readonlyFields: [
      "assets.url",
      "assets.status",
      "assets.provider",
      "assets.model",
      "assets.key",
      "visual.cover",
      "visual.firstScene",
      "publish",
      "generation",
    ],
    patchRootKeys: ["assets"],
    promptGuidance:
      "Focus only on asset prompts and metadata for cover, first-scene, character-reference, style-reference, and runtime-scene assets. Only provide id, kind, title, prompt, characterId, and notes. Never provide url, status, provider, model, key, or generated image identifiers.",
    quickActions: ["补封面提示词", "补首场图提示词", "补角色参考提示词", "整理资产备注"],
    outputMode: "patch",
  },
  {
    id: "interaction",
    label: "互动",
    purpose: "控制玩家参与方式、选择密度、分支策略、自由输入和视觉生成频率。",
    defaultAction: "expand-concept",
    editableFields: [
      "interaction.playMode",
      "interaction.choiceDensity",
      "interaction.branchingMode",
      "interaction.choiceStyle",
      "interaction.branchNotes",
      "interaction.freeformInput",
      "interaction.freeformInputMode",
      "interaction.visualGenerationMode",
    ],
    readonlyFields: ["world", "storyOutline", "assets.url", "publish", "generation"],
    patchRootKeys: ["interaction"],
    promptGuidance:
      "Focus only on concrete play mode, choice density, branching mode, freeform input policy, visual generation mode, choice style, and branch notes. Prefer stable playtestable interaction over complex branching.",
    quickActions: ["优化选项密度", "压缩分支", "明确自由输入", "增强试玩节奏"],
    outputMode: "patch",
  },
  {
    id: "visual",
    label: "视觉",
    purpose: "统一作品视觉风格与运行时风格指南，不直接生成图片文件。",
    defaultAction: "expand-concept",
    editableFields: ["visual.stylePrompt", "runtimePolicy.styleGuide", "interaction.visualGenerationMode"],
    readonlyFields: [
      "visual.cover",
      "visual.firstScene",
      "assets.url",
      "assets.status",
      "characters.referenceImageUrl",
      "publish",
      "generation",
    ],
    patchRootKeys: ["visual", "runtimePolicy", "interaction"],
    promptGuidance:
      "Focus only on visual.stylePrompt, runtimePolicy.styleGuide, and interaction.visualGenerationMode. Do not invent cover URLs, first-scene URLs, asset URLs, or character reference image URLs.",
    quickActions: ["统一视觉风格", "转成生图提示", "降低生图成本", "强化首场氛围"],
    outputMode: "patch",
  },
];

const skillMap = new Map(creatorAssistantSkills.map((skill) => [skill.id, skill]));

export function getCreatorAssistantSkill(
  id: CreatorStoryAssistantTargetSection | undefined,
): CreatorAssistantSkill {
  return skillMap.get(id ?? "project") ?? skillMap.get("project")!;
}

export function isCreatorAssistantSkillId(value: unknown): value is CreatorStoryAssistantTargetSection {
  return typeof value === "string" && skillMap.has(value as CreatorStoryAssistantTargetSection);
}

